use dmantz;
select ENAME ,SAL
FROM EMPLOYEE
WHERE SAL>(select SAL
			FROM EMPLOYEE
            WHERE ENAME='SMITH');
select ENAME ,SAL
FROM EMPLOYEE
WHERE SAL< ( SELECT SAL FROM EMPLOYEE WHERE ENAME='KING');
select ENAME,DEPTNO
FROM EMPLOYEE
WHERE DEPTNO= ( SELECT DEPTNO
				FROM EMPLOYEE
                WHERE ENAME='SMITH');
/*WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF 
EMPLOYEES ARE EARNING MORE THAN ALLEN */
SELECT ENAME,EMPNO
FROM EMPLOYEE
WHERE SAL>( SELECT SAL
			FROM EMPLOYEE
            WHERE ENAME='ALLEN'
            );


/*WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO 
ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN .*/
SELECT ENAME,SAL
FROM EMPLOYEE
WHERE SAL> (SELECT SAL
			FROM EMPLOYEE
            WHERE ENAME='MILLER') AND
        SAL<(SELECT SAL
			FROM EMPLOYEE
            WHERE ENAME='ALLEN');
            
 /*.WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN 
DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH */
SELECT *
FROM EMPLOYEE
WHERE DEPTNO=20 AND
 JOB=(SELECT JOB
	FROM EMPLOYEE
    WHERE ENAME='SMITH');
/*WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS 
MANAGER IN THE SAME DEPT AS TURNER */
   SELECT *
   FROM EMPLOYEE
   WHERE JOB='MANAGER'AND DEPTNO=( SELECT DEPTNO
					FROM EMPLOYEE
                    WHERE ENAME='TURNER');
/*WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED 
AFTER 1980 AND BEFORE KING*/
  SELECT ENAME,HIREDATE
  FROM EMPLOYEE
  WHERE HIREDATE>'1980-12-31' AND
       HIREDATE <( SELECT HIREDATE
					FROM EMPLOYEE
                    WHERE ENAME='KING');
/*WAQTD NAME AND SAL ALONG WITH ANNUAL SAL FOR ALL 
EMPLOYEES WHOS SAL IS LESS THAN BLAKE AND MORE THAN 
3500*/
  SELECT ENAME,SAL*12
  FROM EMPLOYEE
  WHERE SAL>3500 AND SAL< ( SELECT SAL
							FROM EMPLOYEE
                            WHERE ENAME='BLAKE');
 /*WAQTD ALL THE DETAILS OF EMPLOYEES WHO EARN MORE 
THAN SCOTT BUT LESS THAN KING */
SELECT *
FROM EMPLOYEE
WHERE SAL>( select SAL
			FROM EMPLOYEE
            WHERE ENAME='SCOTT') AND
            SAL<( select SAL
			FROM EMPLOYEE
            WHERE ENAME='KING');
 
/*WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS 
WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE */
SELECT *
FROM EMPLOYEE
WHERE ENAME LIKE 'A%'
AND
DEPTNO=(SELECT DEPTNO
			FROM EMPLOYEE
            WHERE ENAME='BLAKES');

/*WAQTD NAME AND COMM IF EMPLOYEES EARN COMISSION 
AND WORK IN THE SAME DESIGNATION AS SMITH*/ 
SELECT ENAME,COMM
FROM EMPLOYEE
WHERE COMM IS NOT NULL AND
		JOB=(SELECT JOB 
				FROM EMPLOYEE
                WHERE ENAME='SMITH');
/*WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS 
CLERK IN THE SAME DEPT AS TURNER .*/
SELECT *
FROM EMPLOYEE
WHERE JOB='CLERK'AND 
      DEPTNO=(select DEPTNO
				FROM EMPLOYEE
                WHERE ENAME='TURNER');
/*WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES 
WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN 
KING. */       
SELECT ENAME,SAL ,JOB
FROM EMPLOYEE
WHERE SAL*12> (select SAL*12
				FROM EMPLOYEE
                WHERE ENAME='SMITH')  
		AND
        SAL*12<(select SAL*12
				FROM EMPLOYEE
                WHERE ENAME='KING')  ;
                
                
                
SELECT DNAME
FROM department
where deptno=(select deptno
				from emp
                where ename='allen');
                
SELECT DLOC
from department  
WHERE DEPTNO=(SELECT DEPTNO
				FROM EMPLOYEE
                WHERE ENAME='ADAMS');  

SELECT ENAME
from EMPLOYEE
WHERE DEPTNO=(SELECT DEPTNO
				FROM DEPARTMENT
                WHERE DLOC='MUMBAI');
                
/*WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION 
IS PRESIDENT */
SELECT DNAME
FROM DEPARTMENT
WHERE DEPTNO=(SELECT DEPTNO 
				FROM EMPLOYEE
                WHERE JOB='PRESIDENT');
/*WAQTD NAMES OF THE EMPLOYEES WORKING IN 
ACCOUNTING DEPARTMENT */
SELECT ENAME
FROM EMPLOYEE
WHERE DEPTNO=(SELECT DEPTNO
				FROM DEPARTMENT
                WHERE Dname='accounting');

/*WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO 
ARE WORKING IN THE LOCATION CHICAGO*/
SELECT ENAME
FROM EMPLOYEE
WHERE DEPTNO=(SELECT DEPTNO
					FROM DEPARTMENT
                    WHERE DLOC='CHICAGO');



/*WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES*/
SELECT *
FROM EMPLOYEE
WHERE DEPTNO=( SELECT DEPTNO
					FROM DEPARTMENT
                    WHERE DNAME='SALES');
/*WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL 
SALARY IF EMPLOYEES ARE WORKING IN NEW YORK */
SELECT*, SAL*12
FROM EMPLOYEE
WHERE DEPTNO=(SELECT DEPTNO
			   FROM DEPARTMENT
               WHERE DLOC='NEW YORK');
/*WAQTD NAMES OF EMPLOYEES WORKING IN 
OPERATIONS DEPARTMENT*/

SELECT ENAME
FROM EMPLOYEE
WHERE DEPTNO=(SELECT DEPTNO
				FROM DEPARTMENT
                WHERE DNAME='SALES');